before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/productive-cli/main.go
    env:
      - CGO_ENABLED=0
env:
  - GO111MODULE=on
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
brews:
  - github:
      owner: mister11
      name: homebrew-productive-cli
    folder: Formula
    homepage: https://github.com/mister11/productive-cli
    description: Productive CLI
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
