// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	config "github.com/mister11/productive-cli/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// ConfigManager is an autogenerated mock type for the ConfigManager type
type ConfigManager struct {
	mock.Mock
}

// GetSavedProjects provides a mock function with given fields:
func (_m *ConfigManager) GetSavedProjects() []config.Project {
	ret := _m.Called()

	var r0 []config.Project
	if rf, ok := ret.Get(0).(func() []config.Project); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.Project)
		}
	}

	return r0
}

// GetToken provides a mock function with given fields:
func (_m *ConfigManager) GetToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetUserID provides a mock function with given fields:
func (_m *ConfigManager) GetUserID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// RemoveExistingProject provides a mock function with given fields: project
func (_m *ConfigManager) RemoveExistingProject(project config.Project) {
	_m.Called(project)
}

// SaveProject provides a mock function with given fields: project
func (_m *ConfigManager) SaveProject(project config.Project) {
	_m.Called(project)
}

// SaveToken provides a mock function with given fields: token
func (_m *ConfigManager) SaveToken(token string) {
	_m.Called(token)
}

// SaveUserID provides a mock function with given fields: userID
func (_m *ConfigManager) SaveUserID(userID string) {
	_m.Called(userID)
}
