// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/mister11/productive-cli/internal/client/model"
	mock "github.com/stretchr/testify/mock"
)

// TrackingClient is an autogenerated mock type for the TrackingClient type
type TrackingClient struct {
	mock.Mock
}

// CreateTimeEntry provides a mock function with given fields: timeEntry
func (_m *TrackingClient) CreateTimeEntry(timeEntry *model.TimeEntry) {
	_m.Called(timeEntry)
}

// GetOrganizationMembership provides a mock function with given fields:
func (_m *TrackingClient) GetOrganizationMembership() []model.OrganizationMembership {
	ret := _m.Called()

	var r0 []model.OrganizationMembership
	if rf, ok := ret.Get(0).(func() []model.OrganizationMembership); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.OrganizationMembership)
		}
	}

	return r0
}

// SearchDeals provides a mock function with given fields: query, dayFormatted
func (_m *TrackingClient) SearchDeals(query string, dayFormatted string) []interface{} {
	ret := _m.Called(query, dayFormatted)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(string, string) []interface{}); ok {
		r0 = rf(query, dayFormatted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// SearchServices provides a mock function with given fields: query, dealID, dayFormatted
func (_m *TrackingClient) SearchServices(query string, dealID string, dayFormatted string) []interface{} {
	ret := _m.Called(query, dealID, dayFormatted)

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(string, string, string) []interface{}); ok {
		r0 = rf(query, dealID, dayFormatted)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}
